/** @enum {string} */
var cgl_resources={
"addc":"vec2 addc(vec2 a,vec2 b){\r\nreturn a+b;\r\n}\r\n",
"addpoints":"vec2 addpoints(vec3 a,vec3 b){\r\nreturn dehomogenize(a) +dehomogenize(b);\r\n}\r\n",
"arccosc":"vec2 arccosc(vec2 a){\r\nvec2 t2=multc(a,negc(a));\r\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\r\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\r\nvec2 erg=addc(multc(logc(tmp1),vec2(0.0,1.0)),vec2(pi*0.5,0.0));\r\nreturn erg;\r\n}\r\n",
"arccosf":"vec2 arccosf(float z){\r\nif(abs(z)<=1.)return vec2(acos(z),0.);\r\nelse if(z>1.)return vec2(0,log(z+sqrt(z*z-1.)));\r\nelse return vec2(pi, -log(-z+sqrt(z*z-1.)));\r\n}\r\n",
"arcsinc":"vec2 arcsinc(vec2 a){\r\nvec2 t2=multc(a,negc(a));\r\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\r\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\r\nvec2 erg=multc(logc(tmp1),vec2(0.0,-1.0));\r\nreturn erg;\r\n}\r\n",
"arcsinf":"vec2 arcsinf(float z){\r\nif(abs(z)<=1.)return vec2(asin(z),0.);\r\nelse if(z>1.)return vec2(pi*.5, -log(z+sqrt(z*z-1.)));\r\nelse return vec2(-pi*.5,log(-z+sqrt(z*z-1.)));\r\n}\r\n",
"arctan2c":"\r\n\r\n\r\n\r\nvec2 arctan2c(vec2 x,vec2 y){\r\nvec2 r=logc(divc(x+vec2(-y.y,y.x),sqrtc(multc(x,x)+multc(y,y))));\r\nreturn vec2(r.y, -r.x);\r\n}\r\n",
"arctan2cvec2":"vec2 arctan2cvec2(cvec2 v){\r\nreturn arctan2c(v.real,v.imag);\r\n}\r\n",
"arctan2vec2":"float arctan2vec2(vec2 v){\r\nreturn atan(v.y,v.x);\r\n}\r\n",
"arctanc":"vec2 arctanc(vec2 a){\r\nvec2 t1=logc(addc(multc(a,vec2(0.0,-1.0)),vec2(1.0,0.0)));\r\nvec2 t2=logc(addc(multc(a,vec2(0.0,1.0)),vec2(1.0,0.0)));\r\nvec2 erg=multc(subc(t1,t2),vec2(0.0,0.5));\r\nreturn erg;\r\n}\r\n",
"blue":"vec3 blue(float f)\r\n{\r\nreturn vec3(0.,0.,clamp(f,0.,1.));\r\n}\r\n",
"cimag":"float imagc(vec2 a){\r\nreturn a.y;\r\n}\r\n",
"conjugate":"vec2 conjugate(vec2 a){\r\nreturn vec2(a.x, -a.y);\r\n}\r\n",
"copytexture_f":"#ifdef GL_ES\r\nprecision highp float;\r\n#endif\r\n\r\nuniform sampler2D sampler;\r\nvarying vec2 cgl_pixel;\r\n\r\nvoid main(void){\r\ngl_FragColor=texture2D(sampler,cgl_pixel);\r\n}\r\n",
"copytexture_v":"attribute vec3 aPos;\r\nattribute vec2 aTexCoord;\r\nvarying vec2 cgl_pixel;\r\n\r\nvoid main(void){\r\ngl_Position=vec4(aPos,1.);\r\ncgl_pixel=aTexCoord;\r\n}\r\n",
"cosc":"vec2 cosc(vec2 a){\r\n\r\nfloat n=exp(a.y);\r\nfloat imag1=n*sin(-a.x);\r\nfloat real1=n*cos(-a.x);\r\nn=exp(-a.y);\r\nfloat imag2=n*sin(a.x);\r\nfloat real2=n*cos(a.x);\r\nfloat i= (imag1+imag2) /2.0;\r\nfloat r= (real1+real2) /2.0;\r\n\r\nreturn vec2(r,i);\r\n}\r\n",
"creal":"float realc(vec2 a){\r\nreturn a.x;\r\n}\r\n",
"dehomogenize":"vec2 dehomogenize(vec3 z){\r\nreturn vec2(z.x,z.y)/z.z;\r\n}\r\n",
"dehomogenizex":"float dehomogenizex(vec3 z){\r\nreturn z.x/z.z;\r\n}\r\n",
"dehomogenizey":"float dehomogenizey(vec3 z){\r\nreturn z.y/z.z;\r\n}\r\n",
"det2":"float det2(mat2 a){\r\nreturn a[0][0]*a[1][1] -a[0][1]*a[1][0];\r\n}\r\n",
"det3":"float det3(mat3 a){\r\nreturn dot(cross(a[0],a[1]),a[2]);\r\n}\r\n",
"det3v":"float det3v(vec3 a,vec3 b,vec3 c){\r\nreturn dot(cross(a,b),c);\r\n}\r\n",
"det4":"float det4(mat4 a){\r\nfloat s00=a[0][0]*a[1][1] -a[0][1]*a[1][0],\r\ns01=a[0][0]*a[1][2] -a[0][2]*a[1][0],\r\ns02=a[0][0]*a[1][3] -a[0][3]*a[1][0],\r\ns03=a[0][1]*a[1][2] -a[0][2]*a[1][1],\r\ns04=a[0][1]*a[1][3] -a[0][3]*a[1][1],\r\ns05=a[0][2]*a[1][3] -a[0][3]*a[1][2],\r\ns06=a[2][0]*a[3][1] -a[2][1]*a[3][0],\r\ns07=a[2][0]*a[3][2] -a[2][2]*a[3][0],\r\ns08=a[2][0]*a[3][3] -a[2][3]*a[3][0],\r\ns09=a[2][1]*a[3][2] -a[2][2]*a[3][1],\r\ns10=a[2][1]*a[3][3] -a[2][3]*a[3][1],\r\ns11=a[2][2]*a[3][3] -a[2][3]*a[3][2];\r\nreturn s00*s11-s01*s10+s02*s09+s03*s08-s04*s07+s05*s06;\r\n}\r\n",
"divc":"vec2 divc(vec2 a,vec2 b){\r\nreturn vec2(dot(a,b),dot(a,vec2(-b.y,b.x)))/dot(b,b);\r\n}\r\n",
"divfc":"vec2 divfc(float a,vec2 b){\r\nreturn a*vec2(b.x,-b.y)/dot(b,b);\r\n}\r\n",
"expc":"vec2 expc(vec2 a){\r\nfloat n=exp(a.x);\r\nfloat r=n*cos(a.y);\r\nfloat i=n*sin(a.y);\r\nreturn vec2(r,i);\r\n}\r\n",
"float2color":"vec4 float2color(float f)\r\n{\r\nreturn vec4(f,f,f,1.);\r\n}\r\n",
"gray":"vec3 gray(float f)\r\n{\r\nf=clamp(f,0.,1.);\r\nreturn vec3(f,f,f);\r\n}\r\n",
"green":"vec3 green(float f)\r\n{\r\nreturn vec3(0.,clamp(f,0.,1.),0.);\r\n}\r\n",
"hsv2rgb":"vec3 hsv2rgb(vec3 c)\r\n{\r\nvec4 K=vec4(1.0,2.0/3.0,1.0/3.0,3.0);\r\nvec3 p=abs(fract(c.xxx+K.xyz) *6.0-K.www);\r\nreturn c.z*mix(K.xxx,clamp(p-K.xxx,0.0,1.0),c.y);\r\n}\r\n",
"hue":"vec3 hue(float a){\r\nreturn hsv2rgb(vec3(a,1.,1.));\r\n}\r\n",
"imagc":"float imagc(vec2 a){\r\nreturn a.y;\r\n}\r\n",
"invc":"vec2 invc(vec2 a){\r\nfloat n=a.x*a.x+a.y*a.y;\r\nreturn vec2(a.x/n,-a.y/n);\r\n}\r\n",
"logc":"vec2 logc(vec2 a){\r\nfloat re=a.x;\r\nfloat im=a.y;\r\nfloat s=sqrt(re*re+im*im);\r\nfloat i=im;\r\nfloat imag=atan(im,re);\r\nif(i<0.0){\r\nimag+= (2.0*pi);\r\n}\r\nif(i==0.0&&re<0.0){\r\nimag=pi;\r\n}\r\nif(imag>pi){\r\nimag-= (2.0*pi);\r\n};\r\nfloat real=log(s);\r\n\r\nreturn vec2(real,imag);\r\n}\r\n",
"logr":"vec2 logr(float a){\r\nif(a>=0.)return vec2(log(a),0);\r\nelse return vec2(log(-a),pi);\r\n}\r\n",
"mat2complex":"mat4 mat2complex(mat2 a)\r\n{\r\nreturn mat4(\r\nvec4(a[0][0],0,a[0][1],0),\r\nvec4(0,a[0][0],0,a[0][1]),\r\nvec4(a[1][0],0,a[1][1],0),\r\nvec4(0,a[1][0],0,a[1][1])\r\n);\r\n}\r\n",
"multc":"vec2 multc(vec2 a,vec2 b){\r\nreturn vec2(dot(a,vec2(b.x,-b.y)),dot(a,b.yx));\r\n}\r\n",
"negc":"vec2 negc(vec2 a){\r\nreturn vec2(-a.x,-a.y);\r\n}\r\n",
"powc":"vec2 powc(vec2 a,vec2 b){\r\nreturn(b.x==0. &&b.y==0.) ?vec2(1.,0.) : ((a.x==0. &&a.y==0.) ?vec2(0.) :expc(multc(logc(a),b)));\r\n}\r\n",
"powi":"float powi(float a,int b){\r\nif(mod(float(b),2.) < .5)\r\nreturn pow(abs(a),float(b));\r\nelse\r\nreturn sign(a)*pow(abs(a),float(b));\r\n}\r\n",
"random":"uniform float rnd_;\r\n\r\nfloat last_rnd= .1231;\r\nfloat random(){\r\nfloat a=fract(132422.21*sin(dot(plain_pixel,343433.671228*vec2(.176574+last_rnd, .1131+rnd_))));\r\nfloat b=fract(last_rnd*2321.2312*sin(dot(plain_pixel+vec2(rnd_,last_rnd),plain_pixel) *43758.5453));\r\nlast_rnd=fract(rnd_ +last_rnd+a+b);\r\nreturn last_rnd;\r\n}\r\n",
"randomnormal":"float randomnormal(){\r\nreturn sqrt(-2. *log(random())) *cos(6.283185307179586*random());\r\n}\r\n",
"realc":"float realc(vec2 a){\r\nreturn a.x;\r\n}\r\n",
"red":"vec3 red(float f)\r\n{\r\nreturn vec3(clamp(f,0.,1.),0.,0.);\r\n}\r\n",
"rgb2hsv":"vec3 rgb2hsv(vec3 c)\r\n{\r\nvec4 K=vec4(0.0, -1.0/3.0,2.0/3.0, -1.0);\r\nvec4 p=mix(vec4(c.bg,K.wz),vec4(c.gb,K.xy),step(c.b,c.g));\r\nvec4 q=mix(vec4(p.xyw,c.r),vec4(c.r,p.yzx),step(p.x,c.r));\r\n\r\nfloat d=q.x-min(q.w,q.y);\r\nfloat e=1.0e-10;\r\nreturn vec3(abs(q.z+ (q.w-q.y) / (6.0*d+e)),d/ (q.x+e),q.x);\r\n}\r\n",
"sinc":"\r\n\r\nvec2 sinc(vec2 a){\r\n\r\nfloat n=exp(a.y);\r\nfloat imag1=n*sin(-a.x);\r\nfloat real1=n*cos(-a.x);\r\nn=exp(-a.y);\r\nfloat imag2=n*sin(a.x);\r\nfloat real2=n*cos(a.x);\r\nfloat r= -(imag1-imag2) /2.0;\r\nfloat i= (real1-real2) /2.0;\r\n\r\nreturn vec2(r,i);\r\n}\r\n",
"sqrtc":"vec2 sqrtc(vec2 a){\r\nreturn expc(multc(logc(a),vec2(0.5,0.0)));\r\n}\r\n",
"sqrtf":"vec2 sqrtf(float a){\r\nif(a>=0.)return vec2(sqrt(a),0.);\r\nelse return vec2(0.,sqrt(-a));\r\n}\r\n",
"standardFragmentHeader":"#ifdef GL_ES\r\nprecision highp float;\r\nprecision highp int;\r\n#endif\r\n\r\n#define pi 3.141592653589793\r\n\r\nvarying vec2 cgl_pixel;\r\nvarying vec2 plain_pixel;\r\n",
"subc":"vec2 subc(vec2 a,vec2 b){\r\nreturn a-b;\r\n}\r\n",
"subpoints":"vec2 subpoints(vec3 a,vec3 b){\r\nreturn dehomogenize(a) -dehomogenize(b);\r\n}\r\n",
"tanc":"vec2 tanc(vec2 a){\r\nvec2 s=sinc(a);\r\nvec2 c=cosc(a);\r\nreturn divc(s,c);\r\n}\r\n",
"vec2complex":"vec4 vec2complex(vec2 a)\r\n{\r\nreturn vec4(a.x,0.,a.y,0);\r\n}\r\n",
"vshader":"attribute vec3 aPos;\r\nattribute vec2 aTexCoord;\r\nvarying vec2 cgl_pixel;\r\nvarying vec2 plain_pixel;\r\nuniform mat3 transformMatrix;\r\nvoid main(void){\r\ngl_Position=vec4(aPos,1.);\r\nplain_pixel=aTexCoord;\r\nvec3 r=transformMatrix*vec3(plain_pixel,1);\r\ncgl_pixel=r.xy/r.z;\r\n}\r\n"
};